Test: Change tests to not rely on "double done" hack
The next commit in this branch for #1511, will disallow adding
tests if `QUnit.done()` and `runEnd` have already happened, thus
leading these hacks to fail as follows:

````
Running "qunit:all" (qunit) task
Testing http://localhost:4000/test/index.html
[…]
Testing http://localhost:4000/test/module-skip.html ....
Error: Unexpected new test after the run already ended
    at new Test (http://localhost:4000/qunit/qunit.js:2206:13)
^C
```

In addition, due to a known issue in grunt-contrib-qunit, these would
also indefinitely hack instead of actually failing.

Ref https://github.com/gruntjs/grunt-contrib-qunit/issues/178.
Ref https://github.com/qunitjs/qunit/issues/1377.
Ref https://github.com/qunitjs/qunit/issues/1511.