CLI: Fix TAP compliance for early errors (e.g. syntax error in test file)
Cherry-picked from 62ca15a2ef3088f836cbcaf315878ea1c7ea59c7 (3.0.0-dev).
> Core: Convert "No tests were run." from fake test to error

Early errors produced output like so:

```
not ok 1 global failure
  ---
  message: ReferenceError: boom is not defined
  stack: |
    ReferenceError: boom is not defined
        at /example.test.js
  ...
Bail out! ReferenceError: boom is not defined
TAP version 13
1..1
```

Instead of:

```
TAP version 13
not ok 1 global failure
  ---
  message: ReferenceError: boom is not defined
  stack: |
    ReferenceError: boom is not defined
        at /example.test.js
  ...
Bail out! ReferenceError: boom is not defined
1..1
```

Because prior to the introduction of the "error" event in 2.17.0,
the only failures were test failures, and those would not begin until
after QUnit.begin() / "runStart" event.