CLI: Fix unhandled `ERR_REQUIRE_ASYNC_MODULE` from async ESM files
Discovered by running the Demos build on Node 22 instead of Node 18,
where it fails as follows:

```
Error: Failed to load file demos/bundlers.mjs
  Error: require() cannot be used on an ESM graph with top-level await. Use import() instead.
    From /home/runner/work/qunit/qunit/src/cli/run.js
    Requiring /home/runner/work/qunit/qunit/demos/bundlers.mjs
```

Ref https://nodejs.org/docs/latest/api/errors.html#err_require_esm
Ref https://github.com/nodejs/node/pull/51977